server:
  port: 9051

# 可以配置api-url ribbon，对以上的服务进行负载均衡
#ribbon:
#  okhttp:
#    enabled: true

spring:
#  redis:
#    host: 139.159.228.191
#    port: 6377
#    password: j4kd4ng3s8f3
#  redis:
#    host: 192.168.88.200
#    port: 5001
#    password:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false




#zuul:
  # 此参数设置忽略哪些服务，如果是*，则忽略所有服务
  # ignoredServices: '*'
  # 此参数可以设置忽略以下的请求
  # ignoredPatterns: /**/admin/**
#  routes:
#    2021_saaf-base-server: /userCenter/**
#  routes:
#    # 如果没有配置路由，则zuul默认已经自动配置类似的关系："/cloud-services-zuul/**":"cloud-services-zuul"
#    # 访问http://127.0.0.1:14601/cloud-services-zuul/zuul-test/simple，等价于 http://127.0.0.1:14606/zuul-test/simple
#    # 此名称任意
#    api-url:
#      # 通过url直接映射
#      # 所有到Zuul的中规则为：/api-a-url/**的访问都映射到http://127.0.0.1:14606/上，
#      # 也就是说当我们访问http://127.0.0.1:14601/api-a-url/zuul-test/simple的时候，Zuul会将该请求路由到：http://127.0.0.1:14606/zuul-test/simple
#      path: /user-center/**
#      # 对于url映射不是通过HystrixCommand执行，也不能通过ribbon进行负载，需要进行额外配置，详细见spring 文档
#      url: http://127.0.0.1:14606/
#    # 此名称任意
#    api-application-name:
#      # 服务名与服务实例地址的关系： 即 http://127.0.0.1:14601//api-a//zuul-test/simple 等介于 http://127.0.0.1:14606/zuul-test/simple
#      path: /user-center/**
#      url: user-center
#    # 此名称任意
#    api-strip-prefix:
#      # http://127.0.0.1:14601/zuul-test/simple 等介于 http://127.0.0.1:14606/zuul-test/simple
#      # 路径请不要使用/zuul测试，这是zuul自己使用的
#      path: /zuul-test/**
#      url: cloud-services-zuul
#      # 默认值为true，如果设置为false，则重定向时，访问的新的URL，不删除path部分的前缀
#      stripPrefix: false

